keys:
  - &xeon_system age1459s0htdl9kvpsyx9y9g2pxrv50emldn6vyzwvv8k7sfhq5s2fus5p69a7
  - &xeon_user age1459s0htdl9kvpsyx9y9g2pxrv50emldn6vyzwvv8k7sfhq5s2fus5p69a7

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *xeon_system
          - *xeon_user
