keys:
  - &xeon_system age1dmcw62n3lc7ppwvstcspardvdj4t383hslc5kpghjpkejzgtw9ssq06k2a
  - &xeon_user age1dmcw62n3lc7ppwvstcspardvdj4t383hslc5kpghjpkejzgtw9ssq06k2a

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *xeon_system
          - *xeon_user
