# Machine-specific hardware config generated by nixos-generate-config.
# Safe to regenerate; avoid manual changes unless you know what you're doing.
{ config, lib, pkgs, modulesPath, ... }:

{
  # Fallbacks for hardware not detected during scanning
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Early boot (initrd) and kernel modules
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Filesystems
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7a48021e-5543-4271-a10e-1c16938e6675";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7351-A245";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # Swap (none configured)
  swapDevices = [ ];

  # DHCP defaults for all interfaces; refine per-interface if needed
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  # Platform and firmware
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
