# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["ahci" "xhci_pci" "ehci_pci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/mnt/windows-c" = {
    device = "/dev/disk/by-uuid/B260A84660A812E1";
    fsType = "ntfs-3g";
    options = ["rw" "uid=1000" "gid=100" "dmask=022" "fmask=133"];
  };

  fileSystems."/mnt/windows-d" = {
    device = "/dev/disk/by-uuid/90B83AF4B83AD904";
    fsType = "ntfs-3g";
    options = ["rw" "uid=1000" "gid=100" "dmask=022" "fmask=133"];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/9b74af6e-4b0d-4041-a543-c4e928af1277";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7DEA-4A88";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  boot.supportedFilesystems = ["ntfs"];

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
